version: '3.9'

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    restart: always
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    ports:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception
