version: '3.8'

volumes:
  wordpress:
      name: wordpress
      driver: local
      driver_opts:
          device: /home/mdella-r/data/wordpress
          o: bind
          type: none
  mariadb:
      name: mariadb
      driver: local
      driver_opts:
          device: /home/mdella-r/data/wordpress
          o: bind
          type: none

networks:
    inception:
        name: inception

services:
  nginx:
    container_name: ngnix
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress-php
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always